spring:
  application:
    name: torqueshare
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: torque-share-db

    redis:
      url: ${REDIS_URL}



  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"



aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION_CODE}
    bucketName: ${AWS_BUCKET_NAME}
